#!/bin/bash
cat src/App.tsx | awk '
/\{globalSearchResults\.employees\.length === 0 && globalSearchResults\.payrolls\.length === 0 \? \(/ {
    print "                {globalSearchResults.employees.length === 0 && globalSearchResults.payrolls.length === 0 && globalSearchResults.contracts.length === 0 && globalSearchResults.tasks.length === 0 ? ("
    print "                  <div className=\"p-4 text-center text-xs text-slate-500 font-medium\">"
    print "                    Nenhum resultado encontrado para a pesquisa."
    print "                  </div>"
    print "                ) : ("
    print "                  <div className=\"max-h-80 overflow-y-auto p-2\">"
    print "                    {globalSearchResults.employees.length > 0 && ("
    print "                      <div className=\"mb-2\">"
    print "                        <h4 className=\"text-[10px] font-bold text-slate-400 uppercase tracking-wider px-3 mb-1\">Funcionários</h4>"
    print "                        <div className=\"space-y-1\">"
    print "                          {globalSearchResults.employees.map(emp => ("
    print "                            <button"
    print "                              key={emp.id}"
    print "                              onClick={() => {"
    print "                                setActiveSection(\"Funcionários\");"
    print "                                setShowSearchResults(false);"
    print "                                setGlobalSearchQuery(\"\");"
    print "                              }}"
    print "                              className=\"w-full text-left flex items-center justify-between p-2 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer\""
    print "                            >"
    print "                              <div>"
    print "                                <p className=\"text-xs font-bold text-slate-800\">{emp.nome}</p>"
    print "                                <p className=\"text-[10px] text-slate-500\">{emp.cargo}</p>"
    print "                              </div>"
    print "                              <span className=\"text-[10px] font-bold text-slate-400 bg-slate-100 px-2 py-0.5 rounded-full\">{emp.codigoFuncionario}</span>"
    print "                            </button>"
    print "                          ))}"
    print "                        </div>"
    print "                      </div>"
    print "                    )}"
    print "                    {globalSearchResults.contracts.length > 0 && ("
    print "                      <div className=\"mb-2\">"
    print "                        <h4 className=\"text-[10px] font-bold text-slate-400 uppercase tracking-wider px-3 mb-1\">Contratos</h4>"
    print "                        <div className=\"space-y-1\">"
    print "                          {globalSearchResults.contracts.map(contract => {"
    print "                            const emp = employees.find(e => e.id === contract.funcionarioId);"
    print "                            return ("
    print "                              <button"
    print "                                key={contract.id}"
    print "                                onClick={() => {"
    print "                                  setActiveSection(\"Contratos\");"
    print "                                  setShowSearchResults(false);"
    print "                                  setGlobalSearchQuery(\"\");"
    print "                                }}"
    print "                                className=\"w-full text-left flex items-center justify-between p-2 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer\""
    print "                              >"
    print "                                <div>"
    print "                                  <p className=\"text-xs font-bold text-slate-800\">{emp?.nome || \"Desconhecido\"}</p>"
    print "                                  <p className=\"text-[10px] text-slate-500\">{contract.tipoContrato}</p>"
    print "                                </div>"
    print "                                <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${contract.status === \"Ativo\" ? \"bg-emerald-100 text-emerald-700\" : \"bg-rose-100 text-rose-700\"}`}>"
    print "                                  {contract.status}"
    print "                                </span>"
    print "                              </button>"
    print "                            );"
    print "                          })}"
    print "                        </div>"
    print "                      </div>"
    print "                    )}"
    print "                    {globalSearchResults.tasks.length > 0 && ("
    print "                      <div className=\"mb-2\">"
    print "                        <h4 className=\"text-[10px] font-bold text-slate-400 uppercase tracking-wider px-3 mb-1\">Atividades</h4>"
    print "                        <div className=\"space-y-1\">"
    print "                          {globalSearchResults.tasks.map(task => {"
    print "                            return ("
    print "                              <button"
    print "                                key={task.id}"
    print "                                onClick={() => {"
    print "                                  setActiveSection(\"Atividades\");"
    print "                                  setShowSearchResults(false);"
    print "                                  setGlobalSearchQuery(\"\");"
    print "                                }}"
    print "                                className=\"w-full text-left flex items-center justify-between p-2 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer\""
    print "                              >"
    print "                                <div>"
    print "                                  <p className=\"text-xs font-bold text-slate-800 line-clamp-1\">{task.titulo}</p>"
    print "                                  <p className=\"text-[10px] text-slate-500\">{task.categoria}</p>"
    print "                                </div>"
    print "                                <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${task.status === \"Completed\" ? \"bg-emerald-100 text-emerald-700\" : \"bg-indigo-100 text-indigo-700\"}`}>"
    print "                                  {task.status === \"Completed\" ? \"Concluído\" : task.status === \"In Progress\" ? \"Em Progresso\" : \"Pendente\"}"
    print "                                </span>"
    print "                              </button>"
    print "                            );"
    print "                          })}"
    print "                        </div>"
    print "                      </div>"
    print "                    )}"
    print "                    {globalSearchResults.payrolls.length > 0 && ("
    print "                      <div>"
    print "                        <h4 className=\"text-[10px] font-bold text-slate-400 uppercase tracking-wider px-3 mb-1\">Folhas de Salário</h4>"
    print "                        <div className=\"space-y-1\">"
    print "                          {globalSearchResults.payrolls.map(pay => ("
    print "                            <button"
    print "                              key={pay.id}"
    print "                              onClick={() => {"
    print "                                setActiveSection(\"Processamento Salarial\");"
    print "                                setShowSearchResults(false);"
    print "                                setGlobalSearchQuery(\"\");"
    print "                              }}"
    print "                              className=\"w-full text-left flex items-center justify-between p-2 hover:bg-slate-50 rounded-xl transition-colors cursor-pointer\""
    print "                            >"
    print "                              <div>"
    print "                                <p className=\"text-xs font-bold text-slate-800\">{pay.funcionarioNome}</p>"
    print "                                <p className=\"text-[10px] text-slate-500\">{pay.periodo}</p>"
    print "                              </div>"
    print "                              <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full ${pay.status === \"Pago\" ? \"bg-emerald-100 text-emerald-700\" : \"bg-amber-100 text-amber-700\"}`}>"
    print "                                {pay.status || \"Pendente\"}"
    print "                              </span>"
    print "                            </button>"
    print "                          ))}"
    print "                        </div>"
    print "                      </div>"
    print "                    )}"
    print "                  </div>"
    print "                )}"
    skip = 1
    next
}
/                  <\/div>/ && skip == 1 {
    getline
    if (match($0, /                \)}/)) {
        skip = 0
        next
    } else {
        print "                  </div>"
        print $0
        next
    }
}
skip == 1 { next }
{ print }
' > src/App.tsx.new && mv src/App.tsx.new src/App.tsx
